# Generated by Django 5.2 on 2025-04-25 08:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text="Client's first name.", max_length=100)),
                ('last_name', models.CharField(help_text="Client's last name.", max_length=100)),
                ('date_of_birth', models.DateField(blank=True, help_text="Client's date of birth.", null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text="Client's gender.", max_length=10)),
                ('contact_number', models.CharField(blank=True, help_text="Client's contact phone number.", max_length=20)),
                ('address', models.TextField(blank=True, help_text="Client's address.")),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthProgram',
            fields=[
                ('program_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the health program (e.g., TB, Malaria, HIV).', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the program.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientEnrollment',
            fields=[
                ('enrollment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes related to the enrollment.')),
                ('client', models.ForeignKey(help_text='Client enrolled in the program.', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='health_app.client')),
                ('program', models.ForeignKey(help_text='Health program the client is enrolled in.', on_delete=django.db.models.deletion.CASCADE, to='health_app.healthprogram')),
            ],
            options={
                'unique_together': {('client', 'program')},
            },
        ),
    ]
